css:
  src: 'css'
  dest: 'css'
  postcss:
    # postcss-cssnext
    cssnext:
      browsers:
        - 'last 2 versions'
        - 'IE 9'
      features:
        colorHwb: false
        colorGray: false
        colorHexAlpha: false
    # postcss-assets
    assets:
      loadPaths:
        - 'fonts/'
        - 'images/'
    # colorguard
    colorguard:
      threshold: '5'
    # cssnano
    cssnano:
      colormin: false
      zindex: false
  extensions:
    - 'css'
