css:
  src: # Set via Yeoman option
  dest: # Set via Yeoman option
  postcss:
    # postcss-cssnext
    cssnext:
      browsers:
        - 'last 2 versions'
        - # Set via Yeoman option
      features:
        colorHwb: false
        colorGray: false
        colorHexAlpha: false
    # postcss-assets
    assets:
      loadPaths:
        - 'fonts/'
        - 'images/'
    # colorguard
    colorguard:
      threshold: '5'
    # cssnano
    cssnano:
      colormin: false
      zindex: false
  extensions:
    - 'css'
